Wip
WildCodeSchool/reims-0919-js-tuk-tuk-travel pull request #2
Opened 2019-12-04 14:37 UTC by blemia51

2019-12-04 15:17 UTC, wasthishelpful commented
make a separate PR for sql files please :)

2019-12-04 17:01 UTC, rocambille requested changes

2019-12-04 17:01 UTC, rocambille commented on bdd/donneesvoyages.md
> +*** Destinations***
remove this file :)

2019-12-04 17:01 UTC, rocambille commented on bdd/tuktuk_v01.sql
> +-- );
dead code: to remove :)

2019-12-05 10:27 UTC, blemia51 commented on bdd/donneesvoyages.md
> +*** Destinations***
Done

2019-12-05 10:27 UTC, blemia51 commented on bdd/tuktuk_v01.sql
> +-- );
Done

2019-12-05 10:27 UTC, merged